const px = (id: number, w = 900, h = 1350) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;

export const pexelsWide = (id: number, w = 1400, h = 900) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=${w}&h=${h}`;

export type SeedProduct = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  priceCents: number;
  compareAtCents: number | null;
  category: string;
  collection: string;
  colorName: string;
  colorHex: string;
  material: string;
  images: string[];
  sizes: string[];
  details: string[];
  badge: string | null;
  ratingX10: number;
  reviewCount: number;
  stock: number;
  isFeatured: boolean;
  sortOrder: number;
};

const APPAREL = ["XS", "S", "M", "L", "XL"];
const APPAREL_XXL = ["XS", "S", "M", "L", "XL", "XXL"];
const ONE_SIZE = ["One Size"];
const SHOES = ["EU 36", "EU 37", "EU 38", "EU 39", "EU 40", "EU 41", "EU 42", "EU 43", "EU 44"];

export const CATEGORIES = [
  "Outerwear",
  "Knitwear",
  "Tailoring",
  "Shirts",
  "Bottoms",
  "Dresses",
  "Bags",
  "Accessories",
  "Shoes",
] as const;

export const COLLECTIONS = ["Atelier Core", "Quiet Season", "Earth Series", "Studio Edit"] as const;

export const SEED_PRODUCTS: SeedProduct[] = [
  // ──────────────────────────────────────────────
  // OUTERWEAR (8 products)
  // ──────────────────────────────────────────────
  {
    slug: "aura-oversized-trench",
    name: "Aura Oversized Trench",
    tagline: "A weightless column of recycled wool.",
    description:
      "Cut long and unlined, the Aura falls in a single uninterrupted line from shoulder to ankle. Woven in Portugal from post-consumer wool and cashmere, it is finished with corozo buttons and a hand-rolled collar that softens with every wear.",
    priceCents: 2499000,
    compareAtCents: 2899000,
    category: "Outerwear",
    collection: "Atelier Core",
    colorName: "Camel Dust",
    colorHex: "#B99977",
    material: "Recycled wool · cashmere",
    images: [px(7760026), px(7760035)],
    sizes: APPAREL,
    details: [
      "72% recycled wool, 28% regenerated cashmere",
      "Unlined, dropped shoulder, hand-rolled collar",
      "Woven in Guimarães, Portugal",
      "Low-impact dye · 8 litres water per garment",
    ],
    badge: "Icon",
    ratingX10: 49,
    reviewCount: 214,
    stock: 18,
    isFeatured: true,
    sortOrder: 1,
  },
  {
    slug: "meridian-wrap-coat",
    name: "Meridian Wrap Coat",
    tagline: "Undyed alpaca, belted at the waist.",
    description:
      "The Meridian is our most quiet silhouette — a self-belted wrap coat in undyed baby alpaca. The fibre arrives in its natural colour, skipping the dye house entirely, so the garment carries the exact tone of the animal it came from.",
    priceCents: 2999000,
    compareAtCents: null,
    category: "Outerwear",
    collection: "Earth Series",
    colorName: "Oat Milk",
    colorHex: "#DFD3C3",
    material: "Undyed baby alpaca",
    images: [px(9619654), px(7760026)],
    sizes: APPAREL,
    details: [
      "100% undyed baby alpaca",
      "Self-tie belt, concealed side pockets",
      "Zero dye, zero bleach",
      "Knitted in Arequipa, Peru",
    ],
    badge: "Zero dye",
    ratingX10: 50,
    reviewCount: 96,
    stock: 11,
    isFeatured: true,
    sortOrder: 2,
  },
  {
    slug: "tempest-quilted-parka",
    name: "Tempest Quilted Parka",
    tagline: "Storm-proof warmth, featherlight feel.",
    description:
      "Insulated with recycled PrimaLoft® and wrapped in an organic cotton-nylon shell that shrugs off rain. The diamond quilt pattern distributes warmth evenly, while the detachable hood adapts to shifting conditions.",
    priceCents: 2149000,
    compareAtCents: null,
    category: "Outerwear",
    collection: "Quiet Season",
    colorName: "Midnight",
    colorHex: "#1E2028",
    material: "Organic cotton-nylon · PrimaLoft®",
    images: [px(6787772), px(6347888)],
    sizes: APPAREL_XXL,
    details: [
      "Shell: 65% organic cotton, 35% recycled nylon",
      "Fill: 100% recycled PrimaLoft® Black Eco",
      "Detachable hood, YKK recycled zips",
      "Water-repellent PFC-free DWR finish",
    ],
    badge: "Best seller",
    ratingX10: 48,
    reviewCount: 327,
    stock: 24,
    isFeatured: false,
    sortOrder: 3,
  },
  {
    slug: "cumulus-down-vest",
    name: "Cumulus Down Vest",
    tagline: "Layering essential in traceable down.",
    description:
      "A slim-fitting vest filled with 700-fill responsibly sourced goose down. The recycled ripstop shell packs down into its own pocket for travel, and every batch of down is traceable to farm level via our partnership with the Responsible Down Standard.",
    priceCents: 1499000,
    compareAtCents: null,
    category: "Outerwear",
    collection: "Earth Series",
    colorName: "Lichen",
    colorHex: "#7A8B6F",
    material: "Recycled ripstop · RDS down",
    images: [px(6932978), px(6626999)],
    sizes: APPAREL,
    details: [
      "100% recycled ripstop nylon shell",
      "700-fill RDS certified goose down",
      "Packable into internal pocket",
      "Snap placket over recycled zip",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 182,
    stock: 32,
    isFeatured: false,
    sortOrder: 4,
  },
  {
    slug: "stratos-mac-coat",
    name: "Stratos Mac Coat",
    tagline: "A modern mac for everyday storms.",
    description:
      "Cut with a relaxed A-line silhouette, the Stratos is an unlined mac coat in waterproof organic cotton bonded to recycled polyester. Raglan sleeves allow easy layering underneath, and the storm flap channels water away from the front placket.",
    priceCents: 1999000,
    compareAtCents: null,
    category: "Outerwear",
    collection: "Studio Edit",
    colorName: "Graphite",
    colorHex: "#4A4A4A",
    material: "Bonded organic cotton",
    images: [px(6311156), px(6311387)],
    sizes: APPAREL,
    details: [
      "Organic cotton bonded to recycled polyester",
      "Waterproof taped seams",
      "Raglan sleeves, storm flap",
      "Made in a wind-powered facility in Lithuania",
    ],
    badge: null,
    ratingX10: 46,
    reviewCount: 89,
    stock: 19,
    isFeatured: false,
    sortOrder: 5,
  },
  {
    slug: "alpine-shearling-jacket",
    name: "Alpine Shearling Jacket",
    tagline: "Rescued shearling, mountain-grade warmth.",
    description:
      "Built from surplus shearling hides rescued from Italian tanneries. The natural curl of the fleece creates air pockets that insulate far beyond their weight, while the suede exterior weathers beautifully over the years.",
    priceCents: 3499000,
    compareAtCents: 3999000,
    category: "Outerwear",
    collection: "Atelier Core",
    colorName: "Cognac",
    colorHex: "#8B5E3C",
    material: "Rescued Italian shearling",
    images: [px(7764079), px(7760035)],
    sizes: APPAREL,
    details: [
      "100% rescued shearling from Italian surplus",
      "Natural fleece lining, suede exterior",
      "Two-way YKK zip, snap collar",
      "Develops unique patina with wear",
    ],
    badge: "Limited",
    ratingX10: 50,
    reviewCount: 45,
    stock: 7,
    isFeatured: true,
    sortOrder: 6,
  },
  {
    slug: "nimbus-rain-shell",
    name: "Nimbus Rain Shell",
    tagline: "Zero-waste rain protection.",
    description:
      "A minimalist rain shell cut from a single panel to eliminate fabric waste. The 3-layer membrane breathes while blocking water, and the seam-sealed construction means every stitch is waterproof. Rolls into its own collar for pocket carry.",
    priceCents: 1299000,
    compareAtCents: null,
    category: "Outerwear",
    collection: "Earth Series",
    colorName: "Storm Blue",
    colorHex: "#4A6178",
    material: "3-layer recycled membrane",
    images: [px(6347888), px(6626882)],
    sizes: APPAREL,
    details: [
      "3-layer recycled polyester membrane",
      "Zero-waste single-panel construction",
      "Fully seam-sealed, PFC-free DWR",
      "Packs into collar pocket",
    ],
    badge: "New",
    ratingX10: 47,
    reviewCount: 64,
    stock: 40,
    isFeatured: false,
    sortOrder: 7,
  },
  {
    slug: "solstice-bomber-jacket",
    name: "Solstice Bomber Jacket",
    tagline: "Classic form, conscious fibre.",
    description:
      "An easy bomber silhouette in organic cotton twill with a satin cupro lining that slides on effortlessly over any layer. The ribbed collar, cuffs, and hem are knitted from recycled cotton yarn, and the antique brass hardware is cast from reclaimed metal.",
    priceCents: 1649000,
    compareAtCents: null,
    category: "Outerwear",
    collection: "Studio Edit",
    colorName: "Army Olive",
    colorHex: "#5C6B4E",
    material: "Organic cotton twill · cupro",
    images: [px(6626999), px(6347888)],
    sizes: APPAREL_XXL,
    details: [
      "100% GOTS organic cotton twill",
      "Cupro lining from cotton linter waste",
      "Recycled cotton rib trim",
      "Reclaimed brass hardware",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 156,
    stock: 28,
    isFeatured: false,
    sortOrder: 8,
  },

  // ──────────────────────────────────────────────
  // KNITWEAR (8 products)
  // ──────────────────────────────────────────────
  {
    slug: "halo-cloud-knit",
    name: "Halo Cloud Knit",
    tagline: "Brushed merino with a halo finish.",
    description:
      "Knitted in a single piece to eliminate off-cuts, the Halo is brushed by hand to raise a soft aura across the surface. Regenerative merino from a closed-loop farm collective in New South Wales.",
    priceCents: 1199000,
    compareAtCents: 1399000,
    category: "Knitwear",
    collection: "Quiet Season",
    colorName: "Dusk Rose",
    colorHex: "#C9A7A7",
    material: "Regenerative merino",
    images: [px(6311612), px(6311613)],
    sizes: APPAREL,
    details: [
      "100% regenerative merino wool",
      "Whole-garment knit · zero waste",
      "Hand-brushed halo finish",
      "Carbon-insetting farm partnership",
    ],
    badge: "Best seller",
    ratingX10: 49,
    reviewCount: 487,
    stock: 30,
    isFeatured: true,
    sortOrder: 9,
  },
  {
    slug: "terra-ribbed-turtleneck",
    name: "Terra Ribbed Turtleneck",
    tagline: "Second-skin rib in organic cotton.",
    description:
      "A fine 2x2 rib that holds its shape through seasons of wear. Dyed with mineral pigments in a closed-loop facility where 96% of the water is recovered and reused.",
    priceCents: 849000,
    compareAtCents: null,
    category: "Knitwear",
    collection: "Earth Series",
    colorName: "Terracotta",
    colorHex: "#A96A4B",
    material: "Organic cotton rib",
    images: [px(6592245), px(6592254)],
    sizes: APPAREL,
    details: [
      "95% organic cotton, 5% elastane",
      "2x2 rib, fold-over neck",
      "Mineral pigment dye",
      "96% water recovery in dyeing",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 158,
    stock: 55,
    isFeatured: false,
    sortOrder: 10,
  },
  {
    slug: "sable-cashmere-cardigan",
    name: "Sable Cashmere Cardigan",
    tagline: "Regenerated cashmere, reborn.",
    description:
      "Spun from reclaimed cashmere fibre, sorted by colour rather than re-dyed. Relaxed through the body with a deep ribbed cuff that stays put.",
    priceCents: 1499000,
    compareAtCents: null,
    category: "Knitwear",
    collection: "Earth Series",
    colorName: "Fawn",
    colorHex: "#CBB295",
    material: "Regenerated cashmere",
    images: [px(9594667), px(9594668)],
    sizes: APPAREL,
    details: [
      "90% regenerated cashmere, 10% wool",
      "Colour-sorted, never re-dyed",
      "Deep rib cuff and hem",
      "Saves 90% water vs. virgin cashmere",
    ],
    badge: "New",
    ratingX10: 49,
    reviewCount: 43,
    stock: 23,
    isFeatured: true,
    sortOrder: 11,
  },
  {
    slug: "zenith-cable-knit-sweater",
    name: "Zenith Cable Knit Sweater",
    tagline: "Heritage cables in modern merino.",
    description:
      "Inspired by fisherman knits but reimagined in extra-fine 19.5-micron merino. Each cable panel is hand-guided on a vintage loom, and the slightly oversized fit makes it the perfect layering piece over a tee or under a blazer.",
    priceCents: 1349000,
    compareAtCents: 1599000,
    category: "Knitwear",
    collection: "Quiet Season",
    colorName: "Cream",
    colorHex: "#F2EDE3",
    material: "Extra-fine merino wool",
    images: [px(6764040), px(6311612)],
    sizes: APPAREL,
    details: [
      "100% extra-fine 19.5μ merino",
      "Hand-guided vintage loom cables",
      "Relaxed fit, ribbed hem and cuffs",
      "Mulesing-free Australian wool",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 201,
    stock: 22,
    isFeatured: false,
    sortOrder: 12,
  },
  {
    slug: "echo-mohair-blend-pullover",
    name: "Echo Mohair Blend Pullover",
    tagline: "Featherweight warmth with a subtle sheen.",
    description:
      "A gossamer-weight pullover in kid mohair and silk that catches light as you move. The loose gauge creates a translucent fabric that layers beautifully and feels almost weightless on the skin.",
    priceCents: 1249000,
    compareAtCents: null,
    category: "Knitwear",
    collection: "Studio Edit",
    colorName: "Lavender Mist",
    colorHex: "#B8A9C9",
    material: "Kid mohair · silk",
    images: [px(7319488), px(7319491)],
    sizes: APPAREL,
    details: [
      "70% South African kid mohair, 30% silk",
      "Loose gauge, semi-sheer",
      "Dropped shoulder, relaxed fit",
      "RMS certified mohair welfare",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 93,
    stock: 35,
    isFeatured: false,
    sortOrder: 13,
  },
  {
    slug: "fjord-half-zip-fleece",
    name: "Fjord Half-Zip Fleece",
    tagline: "Recycled fleece for everyday adventures.",
    description:
      "Made from 100% recycled polyester fleece derived from ocean-bound plastic bottles. The half-zip design lets you regulate warmth, while the anti-pill finish ensures this stays looking fresh season after season.",
    priceCents: 999000,
    compareAtCents: null,
    category: "Knitwear",
    collection: "Earth Series",
    colorName: "Moss",
    colorHex: "#5D6B4E",
    material: "Recycled polyester fleece",
    images: [px(7565115), px(7521137)],
    sizes: APPAREL_XXL,
    details: [
      "100% recycled polyester from ocean-bound plastic",
      "Anti-pill brushed face",
      "Half-zip with chin guard",
      "Each piece diverts 18 bottles from waterways",
    ],
    badge: null,
    ratingX10: 46,
    reviewCount: 274,
    stock: 48,
    isFeatured: false,
    sortOrder: 14,
  },
  {
    slug: "cirrus-cashmere-hoodie",
    name: "Cirrus Cashmere Hoodie",
    tagline: "Luxury comfort meets casual ease.",
    description:
      "The ultimate off-duty piece — a hoodie knitted from grade-A Mongolian cashmere. The double-faced hood keeps its shape without ribbing, and the kangaroo pocket is lined in silk for warmth against bare hands.",
    priceCents: 1699000,
    compareAtCents: null,
    category: "Knitwear",
    collection: "Atelier Core",
    colorName: "Charcoal Mélange",
    colorHex: "#4D4D4D",
    material: "Grade-A Mongolian cashmere",
    images: [px(7679456), px(7208625)],
    sizes: APPAREL,
    details: [
      "100% grade-A Mongolian cashmere",
      "Double-faced hood, no rib edge",
      "Silk-lined kangaroo pocket",
      "Hand-linked seams for flatness",
    ],
    badge: "Luxe",
    ratingX10: 50,
    reviewCount: 119,
    stock: 14,
    isFeatured: false,
    sortOrder: 15,
  },
  {
    slug: "pebble-textured-vest",
    name: "Pebble Textured Vest",
    tagline: "A tactile layer in organic cotton.",
    description:
      "A sleeveless knit vest with a distinctive pebble texture achieved through a complex jacquard technique. Wear it over a crisp shirt or directly on skin for a relaxed summer look.",
    priceCents: 799000,
    compareAtCents: null,
    category: "Knitwear",
    collection: "Studio Edit",
    colorName: "Bone White",
    colorHex: "#EDE8DF",
    material: "Organic cotton jacquard",
    images: [px(6311613), px(6592245)],
    sizes: APPAREL,
    details: [
      "100% GOTS organic cotton",
      "Pebble jacquard texture",
      "Relaxed fit, ribbed armholes",
      "Dyed with plant-based pigments",
    ],
    badge: null,
    ratingX10: 45,
    reviewCount: 67,
    stock: 41,
    isFeatured: false,
    sortOrder: 16,
  },

  // ──────────────────────────────────────────────
  // TAILORING (6 products)
  // ──────────────────────────────────────────────
  {
    slug: "ivory-tailored-blazer",
    name: "Ivory Tailored Blazer",
    tagline: "Deadstock Italian wool, softly structured.",
    description:
      "Built from a limited run of deadstock wool rescued from a Biella mill. Half-canvassed with a natural horsehair interlining so the shoulder moves with the body rather than against it.",
    priceCents: 2299000,
    compareAtCents: null,
    category: "Tailoring",
    collection: "Atelier Core",
    colorName: "Chalk",
    colorHex: "#EFEDE8",
    material: "Deadstock Italian wool",
    images: [px(8484013), px(8148587)],
    sizes: APPAREL,
    details: [
      "Deadstock virgin wool from Biella",
      "Half-canvas construction",
      "Cupro lining from cotton linter",
      "Limited to 180 pieces",
    ],
    badge: "Limited",
    ratingX10: 50,
    reviewCount: 62,
    stock: 9,
    isFeatured: true,
    sortOrder: 17,
  },
  {
    slug: "lumen-minimal-suit",
    name: "Lumen Minimal Suit",
    tagline: "One cloth, two pieces, every season.",
    description:
      "A matched jacket and trouser in a fluid sand-toned cloth made from recycled polyester and Tencel. Machine washable, crease-resistant, and designed to be worn apart as easily as together.",
    priceCents: 3499000,
    compareAtCents: null,
    category: "Tailoring",
    collection: "Atelier Core",
    colorName: "Sand",
    colorHex: "#D7C5AD",
    material: "Tencel · recycled polyester",
    images: [px(36742654), px(8484013)],
    sizes: APPAREL,
    details: [
      "60% Tencel lyocell, 40% recycled polyester",
      "Jacket and trouser set",
      "Machine washable at 30°",
      "Closed-loop lyocell solvent recovery",
    ],
    badge: "Set",
    ratingX10: 48,
    reviewCount: 71,
    stock: 12,
    isFeatured: false,
    sortOrder: 18,
  },
  {
    slug: "eclipse-double-breasted-blazer",
    name: "Eclipse Double-Breasted Blazer",
    tagline: "A modern power silhouette.",
    description:
      "A double-breasted blazer with a slightly cropped length and strong shoulder. Cut from a stretch wool-blend woven in a carbon-neutral mill, with peak lapels that frame the face beautifully.",
    priceCents: 2499000,
    compareAtCents: null,
    category: "Tailoring",
    collection: "Studio Edit",
    colorName: "Deep Navy",
    colorHex: "#1C2333",
    material: "Stretch wool blend",
    images: [px(3622614), px(3812433)],
    sizes: APPAREL,
    details: [
      "96% wool, 4% elastane from Biella",
      "Half-canvas, peak lapels",
      "Slightly cropped length",
      "Carbon-neutral mill production",
    ],
    badge: null,
    ratingX10: 49,
    reviewCount: 84,
    stock: 15,
    isFeatured: false,
    sortOrder: 19,
  },
  {
    slug: "summit-wool-waistcoat",
    name: "Summit Wool Waistcoat",
    tagline: "A three-piece essential, standalone statement.",
    description:
      "A classic waistcoat updated with a modern slim fit and a cupro back panel for breathability. Works beautifully layered over shirts or as a standalone piece with rolled sleeves.",
    priceCents: 1149000,
    compareAtCents: null,
    category: "Tailoring",
    collection: "Atelier Core",
    colorName: "Slate Grey",
    colorHex: "#6B6B6B",
    material: "Italian wool · cupro",
    images: [px(1536619), px(2220316)],
    sizes: APPAREL,
    details: [
      "100% Italian virgin wool front",
      "Cupro back panel for breathability",
      "Slim fit with adjustable back buckle",
      "Horn buttons, fully lined",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 56,
    stock: 20,
    isFeatured: false,
    sortOrder: 20,
  },
  {
    slug: "palazzo-wide-leg-suit-trouser",
    name: "Palazzo Suit Trouser",
    tagline: "Fluid drape, sharp pleat.",
    description:
      "A high-waisted wide-leg trouser with a single front pleat that creates a flowing silhouette. Made from the same Tencel-recycled polyester blend as the Lumen suit, so they can be paired or worn independently.",
    priceCents: 1399000,
    compareAtCents: null,
    category: "Tailoring",
    collection: "Atelier Core",
    colorName: "Pebble",
    colorHex: "#C4B8A8",
    material: "Tencel · recycled polyester",
    images: [px(2897531), px(15906267)],
    sizes: APPAREL,
    details: [
      "60% Tencel lyocell, 40% recycled polyester",
      "High waist with single front pleat",
      "Side-seam pockets, no rear pockets for clean lines",
      "Machine washable at 30°",
    ],
    badge: null,
    ratingX10: 46,
    reviewCount: 92,
    stock: 27,
    isFeatured: false,
    sortOrder: 21,
  },
  {
    slug: "atelier-tuxedo-jacket",
    name: "Atelier Tuxedo Jacket",
    tagline: "Evening elegance, conscious construction.",
    description:
      "A single-breasted tuxedo jacket with silk-satin peak lapels and a grosgrain-trimmed pocket. The body is cut from certified organic wool, and the satin is woven from peace silk for a truly considered evening piece.",
    priceCents: 3899000,
    compareAtCents: null,
    category: "Tailoring",
    collection: "Atelier Core",
    colorName: "Jet Black",
    colorHex: "#0D0D0D",
    material: "Organic wool · peace silk satin",
    images: [px(1040173), px(1040945)],
    sizes: APPAREL,
    details: [
      "GOTS organic wool body",
      "Peace silk satin lapels and trim",
      "Full canvas construction",
      "Hand-finished buttonholes",
    ],
    badge: "Luxe",
    ratingX10: 50,
    reviewCount: 28,
    stock: 8,
    isFeatured: false,
    sortOrder: 22,
  },

  // ──────────────────────────────────────────────
  // SHIRTS (7 products)
  // ──────────────────────────────────────────────
  {
    slug: "atelier-linen-shirt",
    name: "Atelier Linen Shirt",
    tagline: "European flax, washed four times.",
    description:
      "A generous shirt that reads like an artist's smock. Four-stage garment washing gives the flax a lived-in softness from the very first wear, while the mother-of-pearl buttons are sourced from certified shell by-product.",
    priceCents: 749000,
    compareAtCents: null,
    category: "Shirts",
    collection: "Quiet Season",
    colorName: "Raw Ivory",
    colorHex: "#EDE6DA",
    material: "European flax linen",
    images: [px(5384423), px(5384424)],
    sizes: APPAREL,
    details: [
      "100% European flax linen, 180gsm",
      "Four-stage garment wash",
      "Mother-of-pearl buttons",
      "Rain-fed flax from Normandy",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 341,
    stock: 42,
    isFeatured: true,
    sortOrder: 23,
  },
  {
    slug: "horizon-cotton-overshirt",
    name: "Horizon Cotton Overshirt",
    tagline: "The in-between layer.",
    description:
      "Heavier than a shirt, lighter than a jacket. Woven from organic cotton in a dense basketweave that breaks in like a favourite workwear piece.",
    priceCents: 899000,
    compareAtCents: null,
    category: "Shirts",
    collection: "Quiet Season",
    colorName: "Stone",
    colorHex: "#A8A194",
    material: "Organic cotton basketweave",
    images: [px(5393448), px(5393450)],
    sizes: APPAREL,
    details: [
      "100% GOTS organic cotton",
      "Boxy fit, patch chest pockets",
      "Garment dyed in small batches",
      "Repairable · free patch kit",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 167,
    stock: 44,
    isFeatured: false,
    sortOrder: 24,
  },
  {
    slug: "silk-camp-collar-shirt",
    name: "Silk Camp Collar Shirt",
    tagline: "Effortless drape in peace silk.",
    description:
      "A camp collar shirt in washed peace silk that flows like water. The relaxed cut and slightly longer back hem make it work untucked over trousers or shorts, while the silk regulates temperature beautifully in warm weather.",
    priceCents: 1049000,
    compareAtCents: null,
    category: "Shirts",
    collection: "Studio Edit",
    colorName: "Sage",
    colorHex: "#9CAD90",
    material: "Washed peace silk",
    images: [px(5560019), px(5709665)],
    sizes: APPAREL,
    details: [
      "100% peace silk, garment washed",
      "Camp collar, relaxed fit",
      "Coconut shell buttons",
      "Longer back hem for untucked wear",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 112,
    stock: 29,
    isFeatured: false,
    sortOrder: 25,
  },
  {
    slug: "oxford-button-down",
    name: "Oxford Button-Down",
    tagline: "The everyday essential, elevated.",
    description:
      "A classic OCBD in organic cotton oxford cloth with a soft, unstructured collar. Washed once after cutting for a relaxed hand feel that improves with every laundering.",
    priceCents: 649000,
    compareAtCents: null,
    category: "Shirts",
    collection: "Atelier Core",
    colorName: "Powder Blue",
    colorHex: "#A8C4D9",
    material: "Organic cotton oxford",
    images: [px(5876695), px(5876696)],
    sizes: APPAREL_XXL,
    details: [
      "100% GOTS organic cotton oxford, 140gsm",
      "Unstructured button-down collar",
      "Single-needle stitching throughout",
      "Reinforced gusset at side seams",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 389,
    stock: 60,
    isFeatured: false,
    sortOrder: 26,
  },
  {
    slug: "dusk-band-collar-shirt",
    name: "Dusk Band Collar Shirt",
    tagline: "Clean lines, zero fuss.",
    description:
      "A minimalist band collar shirt in a crisp organic poplin. The collarless design eliminates the need for ties and gives a clean, modern neckline that works from studio to dinner.",
    priceCents: 699000,
    compareAtCents: null,
    category: "Shirts",
    collection: "Quiet Season",
    colorName: "Cloud White",
    colorHex: "#F5F0EB",
    material: "Organic cotton poplin",
    images: [px(6069552), px(5384423)],
    sizes: APPAREL,
    details: [
      "100% organic cotton poplin, 120gsm",
      "Band collar, hidden placket",
      "Mother-of-pearl buttons",
      "Slim fit with a gentle taper",
    ],
    badge: null,
    ratingX10: 46,
    reviewCount: 178,
    stock: 37,
    isFeatured: false,
    sortOrder: 27,
  },
  {
    slug: "indigo-chambray-shirt",
    name: "Indigo Chambray Shirt",
    tagline: "Natural indigo, living colour.",
    description:
      "Dyed with natural indigo extracted from Japanese polygonum plants, this chambray shirt fades uniquely with each wash, developing a character entirely its own. The denim-weight fabric bridges the gap between shirt and jacket.",
    priceCents: 799000,
    compareAtCents: null,
    category: "Shirts",
    collection: "Earth Series",
    colorName: "Raw Indigo",
    colorHex: "#2C4A6B",
    material: "Natural indigo chambray",
    images: [px(6186990), px(5560019)],
    sizes: APPAREL,
    details: [
      "100% organic cotton chambray, 180gsm",
      "Natural indigo dye from polygonum",
      "Develops unique fade over time",
      "Chest pocket with reinforced bar tacks",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 146,
    stock: 33,
    isFeatured: false,
    sortOrder: 28,
  },
  {
    slug: "gauze-popover-shirt",
    name: "Gauze Popover Shirt",
    tagline: "Airy cotton for the warmest days.",
    description:
      "An ultra-lightweight popover in double-layer cotton gauze. The two layers create an air gap that keeps you cool, and the half-placket means you pull it on over your head like a tunic.",
    priceCents: 599000,
    compareAtCents: null,
    category: "Shirts",
    collection: "Studio Edit",
    colorName: "Natural",
    colorHex: "#E8DFD0",
    material: "Double-layer cotton gauze",
    images: [px(5393448), px(5384424)],
    sizes: APPAREL,
    details: [
      "100% organic cotton gauze, 90gsm",
      "Double-layer construction for air flow",
      "Half placket, popover style",
      "Pre-shrunk garment wash",
    ],
    badge: "Summer",
    ratingX10: 45,
    reviewCount: 98,
    stock: 52,
    isFeatured: false,
    sortOrder: 29,
  },

  // ──────────────────────────────────────────────
  // BOTTOMS (7 products)
  // ──────────────────────────────────────────────
  {
    slug: "dune-relaxed-trouser",
    name: "Dune Relaxed Trouser",
    tagline: "Hemp twill with a drapey leg.",
    description:
      "Hemp needs no irrigation and returns nutrients to the soil. We blend it with organic cotton for a twill that softens beautifully, cut with a high rise and a wide, fluid leg.",
    priceCents: 899000,
    compareAtCents: null,
    category: "Bottoms",
    collection: "Earth Series",
    colorName: "Dune",
    colorHex: "#C8B49A",
    material: "Hemp · organic cotton twill",
    images: [px(15906267), px(2897531)],
    sizes: APPAREL,
    details: [
      "55% hemp, 45% organic cotton",
      "High rise, wide leg, side-seam pockets",
      "Rain-fed hemp, no irrigation",
      "Sewn in a Fair Trade certified facility",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 203,
    stock: 38,
    isFeatured: false,
    sortOrder: 30,
  },
  {
    slug: "umber-tapered-chino",
    name: "Umber Tapered Chino",
    tagline: "A modern chino that moves with you.",
    description:
      "Made from organic cotton with a touch of stretch, the Umber sits at the true waist and tapers gently to the ankle. Garment dyed for a rich, lived-in colour that deepens with each wash.",
    priceCents: 749000,
    compareAtCents: null,
    category: "Bottoms",
    collection: "Atelier Core",
    colorName: "Tobacco",
    colorHex: "#7A5A3A",
    material: "Organic stretch cotton",
    images: [px(1749452), px(2065195)],
    sizes: APPAREL_XXL,
    details: [
      "97% organic cotton, 3% elastane",
      "True waist, tapered leg",
      "Garment dyed in small batches",
      "YKK recycled zip fly",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 256,
    stock: 45,
    isFeatured: false,
    sortOrder: 31,
  },
  {
    slug: "selvedge-raw-denim",
    name: "Selvedge Raw Denim",
    tagline: "Japanese selvedge, your fade story.",
    description:
      "Woven on vintage shuttle looms in Okayama, Japan, this 14oz raw selvedge denim is designed to fade beautifully over years of wear. The fabric is stiff at first, then moulds to your body, creating a truly personal garment.",
    priceCents: 999000,
    compareAtCents: null,
    category: "Bottoms",
    collection: "Atelier Core",
    colorName: "Raw Indigo",
    colorHex: "#1A2744",
    material: "Japanese selvedge denim",
    images: [px(2002717), px(1749452)],
    sizes: APPAREL_XXL,
    details: [
      "100% cotton, 14oz Japanese selvedge",
      "Woven on vintage shuttle looms in Okayama",
      "Raw / unwashed — no pre-distressing",
      "Chain-stitched hem, hidden selvedge coin pocket",
    ],
    badge: "Heritage",
    ratingX10: 49,
    reviewCount: 312,
    stock: 20,
    isFeatured: false,
    sortOrder: 32,
  },
  {
    slug: "drift-pleated-shorts",
    name: "Drift Pleated Shorts",
    tagline: "Breezy tailored shorts in linen.",
    description:
      "A single front pleat gives these shorts a dressier look than a flat-front, while the linen fabric keeps you cool in the heat. The 7-inch inseam hits above the knee for a modern proportion.",
    priceCents: 599000,
    compareAtCents: null,
    category: "Bottoms",
    collection: "Studio Edit",
    colorName: "Ecru",
    colorHex: "#D9CEBD",
    material: "European flax linen",
    images: [px(2065195), px(15906267)],
    sizes: APPAREL,
    details: [
      "100% European flax linen",
      'Single front pleat, 7" inseam',
      "Side-seam and rear welt pockets",
      "Elasticated back waistband for comfort",
    ],
    badge: "Summer",
    ratingX10: 46,
    reviewCount: 134,
    stock: 42,
    isFeatured: false,
    sortOrder: 33,
  },
  {
    slug: "zenith-drawstring-trousers",
    name: "Zenith Drawstring Trousers",
    tagline: "Relaxed luxury, all-day comfort.",
    description:
      "A pull-on trouser in a fluid viscose-linen blend with a drawstring waist and a gentle taper. Designed to travel well and look polished without trying too hard.",
    priceCents: 849000,
    compareAtCents: null,
    category: "Bottoms",
    collection: "Quiet Season",
    colorName: "Smoke",
    colorHex: "#8B8680",
    material: "Viscose-linen blend",
    images: [px(2529148), px(2897531)],
    sizes: APPAREL,
    details: [
      "55% EcoVero viscose, 45% linen",
      "Drawstring waist with internal elastic",
      "Gentle taper to ankle",
      "Wrinkle-resistant for travel",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 189,
    stock: 36,
    isFeatured: false,
    sortOrder: 34,
  },
  {
    slug: "cargo-utility-pant",
    name: "Cargo Utility Pant",
    tagline: "Functional pockets, organic fabric.",
    description:
      "A workwear-inspired cargo pant with six pockets, including bellowed side pockets that sit flat when empty. Made from a heavy organic cotton ripstop that softens with every wash but refuses to quit.",
    priceCents: 949000,
    compareAtCents: null,
    category: "Bottoms",
    collection: "Studio Edit",
    colorName: "Olive Drab",
    colorHex: "#5A5E42",
    material: "Organic cotton ripstop",
    images: [px(2983464), px(2529148)],
    sizes: APPAREL_XXL,
    details: [
      "100% organic cotton ripstop, 260gsm",
      "Six pockets including bellowed cargo",
      "Reinforced knee panels",
      "Triple-stitched stress points",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 221,
    stock: 31,
    isFeatured: false,
    sortOrder: 35,
  },
  {
    slug: "lounge-knit-jogger",
    name: "Lounge Knit Jogger",
    tagline: "Cashmere comfort, jogger ease.",
    description:
      "A knitted jogger in recycled cashmere with a smooth single-jersey face and a brushed interior. Ribbed cuffs and waistband keep things secure, while the relaxed fit means pure comfort from couch to café.",
    priceCents: 799000,
    compareAtCents: null,
    category: "Bottoms",
    collection: "Quiet Season",
    colorName: "Heather Grey",
    colorHex: "#A8A5A0",
    material: "Recycled cashmere jersey",
    images: [px(3206171), px(2529148)],
    sizes: APPAREL,
    details: [
      "80% recycled cashmere, 20% wool",
      "Single-jersey face, brushed interior",
      "Ribbed cuffs and waistband",
      "Internal drawstring cord",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 167,
    stock: 25,
    isFeatured: false,
    sortOrder: 36,
  },

  // ──────────────────────────────────────────────
  // DRESSES (5 products)
  // ──────────────────────────────────────────────
  {
    slug: "noir-silk-slip-dress",
    name: "Noir Silk Slip Dress",
    tagline: "Peace silk on the true bias.",
    description:
      "Cut on the bias so the fabric does the shaping. Our peace silk is harvested after the moth has left the cocoon, producing a slightly irregular, luminous yarn with real depth.",
    priceCents: 1699000,
    compareAtCents: 1999000,
    category: "Dresses",
    collection: "Atelier Core",
    colorName: "Ink",
    colorHex: "#1B1A18",
    material: "Peace silk charmeuse",
    images: [px(18516743), px(3289711)],
    sizes: APPAREL,
    details: [
      "100% peace (ahimsa) silk",
      "True bias cut, adjustable straps",
      "French seams throughout",
      "Hand-finished hem",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 129,
    stock: 21,
    isFeatured: false,
    sortOrder: 37,
  },
  {
    slug: "willow-wrap-dress",
    name: "Willow Wrap Dress",
    tagline: "Universally flattering, endlessly versatile.",
    description:
      "A classic wrap dress in a fluid EcoVero viscose that drapes beautifully. The self-tie belt allows you to adjust the fit, and the midi length works from office to evening without a change.",
    priceCents: 1349000,
    compareAtCents: null,
    category: "Dresses",
    collection: "Quiet Season",
    colorName: "Burgundy",
    colorHex: "#6B2D3E",
    material: "EcoVero viscose",
    images: [px(3289711), px(3312671)],
    sizes: APPAREL,
    details: [
      "100% Lenzing EcoVero viscose",
      "True wrap with self-tie belt",
      "Midi length, V-neckline",
      "50% lower water and emissions vs. conventional viscose",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 197,
    stock: 33,
    isFeatured: false,
    sortOrder: 38,
  },
  {
    slug: "bloom-tiered-maxi-dress",
    name: "Bloom Tiered Maxi Dress",
    tagline: "Organic cotton tiers that catch every breeze.",
    description:
      "A voluminous maxi dress with three gathered tiers that create beautiful movement. Made from lightweight organic cotton voile, it is equally at home at a garden party or a beach walkway.",
    priceCents: 1499000,
    compareAtCents: null,
    category: "Dresses",
    collection: "Studio Edit",
    colorName: "Terracotta Bloom",
    colorHex: "#C57A5A",
    material: "Organic cotton voile",
    images: [px(3312671), px(3622888)],
    sizes: APPAREL,
    details: [
      "100% GOTS organic cotton voile",
      "Three gathered tiers, full maxi length",
      "Smocked bodice with adjustable straps",
      "Block-printed using natural dyes",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 108,
    stock: 26,
    isFeatured: false,
    sortOrder: 39,
  },
  {
    slug: "column-knit-midi-dress",
    name: "Column Knit Midi Dress",
    tagline: "Structured knit, minimal seams.",
    description:
      "A body-skimming midi dress knitted in a single piece from organic cotton with a touch of stretch. The column silhouette elongates the frame, and the ribbed neckline sits cleanly without gaping.",
    priceCents: 1199000,
    compareAtCents: null,
    category: "Dresses",
    collection: "Atelier Core",
    colorName: "Espresso",
    colorHex: "#3D2B1F",
    material: "Organic cotton knit",
    images: [px(3622888), px(3714459)],
    sizes: APPAREL,
    details: [
      "95% organic cotton, 5% elastane",
      "Whole-garment seamless knit",
      "Midi length, ribbed neckline",
      "Machine washable at 30°",
    ],
    badge: null,
    ratingX10: 46,
    reviewCount: 86,
    stock: 30,
    isFeatured: false,
    sortOrder: 40,
  },
  {
    slug: "linen-shirt-dress",
    name: "Linen Shirt Dress",
    tagline: "A day dress with workwear DNA.",
    description:
      "Based on our bestselling Atelier Linen Shirt, extended to knee length with a self-fabric belt. The same four-stage garment wash gives it instant softness, and the patch pockets add functional charm.",
    priceCents: 1249000,
    compareAtCents: null,
    category: "Dresses",
    collection: "Earth Series",
    colorName: "Oatmeal",
    colorHex: "#D3C8B8",
    material: "European flax linen",
    images: [px(3714459), px(18516743)],
    sizes: APPAREL,
    details: [
      "100% European flax linen, 180gsm",
      "Knee length with self-fabric belt",
      "Patch chest and hip pockets",
      "Mother-of-pearl buttons",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 154,
    stock: 35,
    isFeatured: false,
    sortOrder: 41,
  },

  // ──────────────────────────────────────────────
  // BAGS (6 products)
  // ──────────────────────────────────────────────
  {
    slug: "soleil-woven-tote",
    name: "Soleil Woven Tote",
    tagline: "A day bag that outlives trends.",
    description:
      "Vegetable-tanned leather from a Tuscan tannery using bark and tree extracts instead of chromium. The woven body is assembled by a single artisan in roughly four hours.",
    priceCents: 1699000,
    compareAtCents: null,
    category: "Bags",
    collection: "Atelier Core",
    colorName: "Tobacco",
    colorHex: "#8A6243",
    material: "Vegetable-tanned leather",
    images: [px(26316185), px(9595073)],
    sizes: ONE_SIZE,
    details: [
      "Vegetable-tanned Tuscan leather",
      "Hand-woven body · 4 hours per bag",
      "Unlined, solid brass hardware",
      "Lifetime repair included",
    ],
    badge: "Hand-woven",
    ratingX10: 49,
    reviewCount: 88,
    stock: 14,
    isFeatured: true,
    sortOrder: 42,
  },
  {
    slug: "petra-leather-crossbody",
    name: "Petra Leather Crossbody",
    tagline: "Small, structured, endlessly useful.",
    description:
      "A compact crossbody with a magnetic closure and an adjustable strap that converts to a shoulder carry. Made from off-cuts rescued from our tote production.",
    priceCents: 1449000,
    compareAtCents: null,
    category: "Bags",
    collection: "Quiet Season",
    colorName: "Chestnut",
    colorHex: "#7A5236",
    material: "Rescued leather off-cuts",
    images: [px(9595073), px(7953286)],
    sizes: ONE_SIZE,
    details: [
      "Made from rescued production off-cuts",
      "Magnetic closure, interior card slot",
      "Convertible adjustable strap",
      "Solid brass hardware",
    ],
    badge: null,
    ratingX10: 46,
    reviewCount: 74,
    stock: 26,
    isFeatured: false,
    sortOrder: 43,
  },
  {
    slug: "ember-structured-satchel",
    name: "Ember Structured Satchel",
    tagline: "Architectural lines, softened edges.",
    description:
      "A satchel with a quietly architectural shape, built on a frame of compressed recycled board and wrapped in supple vegetable-tanned hide. Fits a 13\" laptop with room to spare.",
    priceCents: 1899000,
    compareAtCents: null,
    category: "Bags",
    collection: "Atelier Core",
    colorName: "Obsidian",
    colorHex: "#23201D",
    material: "Vegetable-tanned hide",
    images: [px(7953286), px(3839904)],
    sizes: ONE_SIZE,
    details: [
      'Fits a 13" laptop',
      "Recycled board frame",
      "Hand-burnished edges",
      "Lifetime repair included",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 51,
    stock: 17,
    isFeatured: false,
    sortOrder: 44,
  },
  {
    slug: "canvas-weekender",
    name: "Canvas Weekender",
    tagline: "The only bag for a short trip.",
    description:
      "An oversized duffle in heavyweight organic canvas with vegetable-tanned leather handles and a detachable shoulder strap. The interior shoe compartment keeps trainers separate, and the brass feet protect the base.",
    priceCents: 1599000,
    compareAtCents: null,
    category: "Bags",
    collection: "Studio Edit",
    colorName: "Washed Khaki",
    colorHex: "#B5A88E",
    material: "Organic canvas · vegetable-tanned leather",
    images: [px(3839904), px(3907517)],
    sizes: ONE_SIZE,
    details: [
      "18oz organic cotton canvas",
      "Vegetable-tanned leather trim",
      "Interior shoe compartment",
      "Solid brass feet and hardware",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 137,
    stock: 19,
    isFeatured: false,
    sortOrder: 45,
  },
  {
    slug: "micro-belt-bag",
    name: "Micro Belt Bag",
    tagline: "Hands-free and effortlessly chic.",
    description:
      "A compact belt bag in soft grained leather that clips at the waist or slings across the chest. Just enough room for phone, cards, keys, and lip balm — everything you need, nothing you don't.",
    priceCents: 999000,
    compareAtCents: null,
    category: "Bags",
    collection: "Studio Edit",
    colorName: "Noir",
    colorHex: "#1A1A1A",
    material: "Grained vegetable-tanned leather",
    images: [px(3907517), px(3951830)],
    sizes: ONE_SIZE,
    details: [
      "Full-grain vegetable-tanned leather",
      "Adjustable strap for waist or crossbody",
      "YKK recycled zip closure",
      "Interior card slot and key clip",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 203,
    stock: 34,
    isFeatured: false,
    sortOrder: 46,
  },
  {
    slug: "studio-laptop-sleeve",
    name: "Studio Laptop Sleeve",
    tagline: "Protection with a patina.",
    description:
      "A padded laptop sleeve in vegetable-tanned leather with a wool felt lining that cushions your device. The magnetic closure is seamless, and the exterior pocket holds cables and chargers.",
    priceCents: 799000,
    compareAtCents: null,
    category: "Bags",
    collection: "Atelier Core",
    colorName: "Tan",
    colorHex: "#C19A6B",
    material: "Vegetable-tanned leather · wool felt",
    images: [px(3951830), px(9595073)],
    sizes: ONE_SIZE,
    details: [
      'Fits 13" and 14" laptops',
      "Vegetable-tanned leather exterior",
      "Wool felt interior padding",
      "Magnetic closure, exterior cable pocket",
    ],
    badge: null,
    ratingX10: 46,
    reviewCount: 89,
    stock: 28,
    isFeatured: false,
    sortOrder: 47,
  },

  // ──────────────────────────────────────────────
  // ACCESSORIES (5 products)
  // ──────────────────────────────────────────────
  {
    slug: "alpaca-oversized-scarf",
    name: "Alpaca Oversized Scarf",
    tagline: "A blanket you can wear.",
    description:
      "An oversized scarf in undyed baby alpaca that doubles as a travel blanket. The natural colour variation in the fibre creates a heathered effect without any dye, and the fringe is hand-tied by the weavers in Peru.",
    priceCents: 699000,
    compareAtCents: null,
    category: "Accessories",
    collection: "Earth Series",
    colorName: "Natural Heather",
    colorHex: "#C4B8A4",
    material: "Undyed baby alpaca",
    images: [px(4066293), px(4380970)],
    sizes: ONE_SIZE,
    details: [
      "100% undyed baby alpaca",
      "Oversized: 200cm × 70cm",
      "Hand-tied fringe",
      "Woven by artisans in Cusco, Peru",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 142,
    stock: 39,
    isFeatured: false,
    sortOrder: 48,
  },
  {
    slug: "merino-beanie",
    name: "Merino Beanie",
    tagline: "Itch-free warmth in 18.5μ merino.",
    description:
      "A ribbed beanie in ultra-fine 18.5-micron merino wool that is so soft it can be worn directly on skin without any itch. The double-layer construction provides warmth without bulk, and the turn-back cuff can be adjusted.",
    priceCents: 349000,
    compareAtCents: null,
    category: "Accessories",
    collection: "Quiet Season",
    colorName: "Charcoal",
    colorHex: "#3A3A3A",
    material: "Ultra-fine merino wool",
    images: [px(4947034), px(9558136)],
    sizes: ONE_SIZE,
    details: [
      "100% mulesing-free 18.5μ merino",
      "Double-layer ribbed construction",
      "Adjustable turn-back cuff",
      "Knitted in Scotland",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 318,
    stock: 56,
    isFeatured: false,
    sortOrder: 49,
  },
  {
    slug: "silk-pocket-square-set",
    name: "Silk Pocket Square Set",
    tagline: "Three squares, infinite combinations.",
    description:
      "A set of three pocket squares in peace silk, each dyed with a different natural pigment — indigo, madder root, and walnut shell. Hand-rolled edges and a matte finish that looks effortlessly elegant.",
    priceCents: 399000,
    compareAtCents: null,
    category: "Accessories",
    collection: "Atelier Core",
    colorName: "Trio Set",
    colorHex: "#7B6B5D",
    material: "Peace silk · natural dyes",
    images: [px(10679171), px(10838413)],
    sizes: ONE_SIZE,
    details: [
      "100% peace silk, 12mm weight",
      "Set of three: indigo, madder, walnut",
      "Hand-rolled edges",
      "Natural plant-based dyes",
    ],
    badge: "Set",
    ratingX10: 46,
    reviewCount: 67,
    stock: 43,
    isFeatured: false,
    sortOrder: 50,
  },
  {
    slug: "reversible-leather-belt",
    name: "Reversible Leather Belt",
    tagline: "Two belts in one, built forever.",
    description:
      "A reversible belt with vegetable-tanned black on one side and rich tan on the other. The rotating buckle clicks between sides, giving you two looks from a single piece. Solid brass buckle, no nickel plating to wear off.",
    priceCents: 499000,
    compareAtCents: null,
    category: "Accessories",
    collection: "Atelier Core",
    colorName: "Black / Tan",
    colorHex: "#2A2A2A",
    material: "Vegetable-tanned leather",
    images: [px(10679171), px(11011218)],
    sizes: ["S (28-30)", "M (32-34)", "L (36-38)", "XL (40-42)"],
    details: [
      "Full-grain vegetable-tanned leather",
      "Reversible: black and tan sides",
      "Solid brass rotating buckle",
      "35mm width, hand-burnished edges",
    ],
    badge: null,
    ratingX10: 48,
    reviewCount: 234,
    stock: 41,
    isFeatured: false,
    sortOrder: 51,
  },
  {
    slug: "cashmere-gloves",
    name: "Cashmere Gloves",
    tagline: "Touchscreen-compatible luxury.",
    description:
      "Knitted from regenerated cashmere with conductive yarn in the thumb and index finger for touchscreen use. The ribbed cuff extends under jacket sleeves to seal out drafts, and the full-fashioned knit means no seams across the fingertips.",
    priceCents: 449000,
    compareAtCents: null,
    category: "Accessories",
    collection: "Quiet Season",
    colorName: "Camel",
    colorHex: "#C4A97D",
    material: "Regenerated cashmere",
    images: [px(11011218), px(11052653)],
    sizes: ["S/M", "M/L"],
    details: [
      "90% regenerated cashmere, 10% conductive yarn",
      "Touchscreen-compatible thumb and index finger",
      "Full-fashioned seamless fingertips",
      "Extended ribbed cuff",
    ],
    badge: null,
    ratingX10: 47,
    reviewCount: 156,
    stock: 37,
    isFeatured: false,
    sortOrder: 52,
  },

  // ──────────────────────────────────────────────
  // SHOES (5 products)
  // ──────────────────────────────────────────────
  {
    slug: "atlas-leather-derby",
    name: "Atlas Leather Derby",
    tagline: "A resoleable shoe for every decade.",
    description:
      "A classic derby shoe in vegetable-tanned leather with a Goodyear welted sole that can be resoled indefinitely. The cork filler moulds to your foot over time, and the leather develops a rich patina that tells your story.",
    priceCents: 1649000,
    compareAtCents: null,
    category: "Shoes",
    collection: "Atelier Core",
    colorName: "Dark Brown",
    colorHex: "#3E2723",
    material: "Vegetable-tanned leather",
    images: [px(11124742), px(1462637)],
    sizes: SHOES,
    details: [
      "Full-grain vegetable-tanned calfskin",
      "Goodyear welted construction",
      "Natural cork filler, leather insole",
      "Resoleable for a lifetime of wear",
    ],
    badge: "Heritage",
    ratingX10: 49,
    reviewCount: 94,
    stock: 16,
    isFeatured: false,
    sortOrder: 53,
  },
  {
    slug: "canvas-espadrille",
    name: "Canvas Espadrille",
    tagline: "Organic cotton, hand-stitched jute.",
    description:
      "A hand-stitched espadrille in organic cotton canvas with a natural jute sole. Made by a family workshop in the Basque Country that has been crafting espadrilles for four generations. Biodegradable at end of life.",
    priceCents: 699000,
    compareAtCents: null,
    category: "Shoes",
    collection: "Earth Series",
    colorName: "Navy",
    colorHex: "#1E2A3A",
    material: "Organic cotton canvas · jute",
    images: [px(13909747), px(1152077)],
    sizes: SHOES,
    details: [
      "100% organic cotton canvas upper",
      "Hand-stitched natural jute sole",
      "Made by a family in the Basque Country",
      "Fully biodegradable at end of life",
    ],
    badge: null,
    ratingX10: 46,
    reviewCount: 207,
    stock: 48,
    isFeatured: false,
    sortOrder: 54,
  },
  {
    slug: "suede-chelsea-boot",
    name: "Suede Chelsea Boot",
    tagline: "Rain-proof suede, timeless silhouette.",
    description:
      "A Chelsea boot in water-resistant suede with a Goodyear welted commando sole. The elastic gussets use recycled yarn, and the pull tab is made from vegetable-tanned leather. Designed to handle city streets and country lanes equally well.",
    priceCents: 1899000,
    compareAtCents: null,
    category: "Shoes",
    collection: "Quiet Season",
    colorName: "Mushroom",
    colorHex: "#8B7D6B",
    material: "Water-resistant suede",
    images: [px(16170392), px(1462637)],
    sizes: SHOES,
    details: [
      "Water-resistant suede upper",
      "Goodyear welted commando sole",
      "Recycled elastic gussets",
      "Resoleable and repairable",
    ],
    badge: null,
    ratingX10: 49,
    reviewCount: 163,
    stock: 13,
    isFeatured: false,
    sortOrder: 55,
  },
  {
    slug: "knit-runner-sneaker",
    name: "Knit Runner Sneaker",
    tagline: "Ocean plastic, cloud comfort.",
    description:
      "An ultralight runner knitted from yarn spun from ocean-recovered plastic. The sugarcane-based EVA midsole provides cushioned support, and the natural rubber outsole grips wet surfaces. Machine washable for easy care.",
    priceCents: 999000,
    compareAtCents: null,
    category: "Shoes",
    collection: "Studio Edit",
    colorName: "Fog Grey",
    colorHex: "#B5B0AB",
    material: "Ocean plastic knit · sugarcane EVA",
    images: [px(1152077), px(13909747)],
    sizes: SHOES,
    details: [
      "Upper: 100% ocean-recovered plastic yarn",
      "Midsole: sugarcane-based EVA",
      "Outsole: natural rubber",
      "Machine washable at 30°",
    ],
    badge: "New",
    ratingX10: 47,
    reviewCount: 284,
    stock: 42,
    isFeatured: false,
    sortOrder: 56,
  },
  {
    slug: "leather-loafer",
    name: "Leather Loafer",
    tagline: "Slip on, step out.",
    description:
      "A penny loafer in hand-burnished vegetable-tanned leather with a Blake-stitched leather sole. The unlined construction lets the leather breathe and mould to your foot, while the hand-painted finish develops depth over time.",
    priceCents: 1599000,
    compareAtCents: null,
    category: "Shoes",
    collection: "Atelier Core",
    colorName: "Cordovan",
    colorHex: "#622C2C",
    material: "Hand-burnished vegetable-tanned leather",
    images: [px(1462637), px(1549200)],
    sizes: SHOES,
    details: [
      "Hand-burnished vegetable-tanned calfskin",
      "Blake-stitched leather sole",
      "Unlined for breathability",
      "Hand-painted finish, unique to each pair",
    ],
    badge: null,
    ratingX10: 49,
    reviewCount: 78,
    stock: 15,
    isFeatured: false,
    sortOrder: 57,
  },
];

export const EDITORIAL_IMAGES = {
  atelier: pexelsWide(7256872, 1400, 1000),
  fabric: pexelsWide(35009340, 1200, 900),
  studio: pexelsWide(9849932, 1200, 900),
  pins: pexelsWide(7256913, 1200, 900),
};
